#!/bin/zsh
exec swayidle -w \
    timeout 305 'hyprctl dispatch dpms off' \
    resume 'hyprctl dispatch dpms on' \
    before-sleep 'playerctl pause' \
    before-sleep 'zsh $HOME/.config/hypr/lock.zsh'

